name: 'Prepare macOS Job'
description: 'Gets app token, checks out code, and sets up credentials/certificates for macOS workflows'
inputs:
  app-id:
    description: 'GitHub App ID'
    required: true
  app-private-key:
    description: 'GitHub App Private Key'
    required: true
  owner:
    description: 'Repository owner'
    required: true
  keychain-name:
    description: 'Keychain name to use'
    required: true
  macos-certificates:
    description: 'macOS developer certificates in base64'
    required: true
  macos-certificates-password:
    description: 'Password for macOS certificates'
    required: true

runs:
  using: "composite"
  steps:
   - name: Get private repos app token
     id: hedge-private-repos
     uses: actions/create-github-app-token@v1
     with:
       app-id: ${{ inputs.app-id }}
       private-key: ${{ inputs.app-private-key }}
       owner: ${{ inputs.owner }}

   - name: Checkout code
     uses: actions/checkout@v4
     with:
       fetch-depth: 0
       fetch-tags: true
       submodules: recursive
       token: ${{ steps.hedge-private-repos.outputs.token }}

   - name: Configure Git credential helper
     shell: bash
     run: |
       git config --global credential.helper store
       echo "https://x-access-token:${{ inputs.github-token }}@github.com" > ~/.git-credentials

   - name: Import Codesign Certificates
     uses: apple-actions/import-codesign-certs@v3
     with:
       keychain: ${{ inputs.keychain-name }}
       p12-file-base64: ${{ inputs.macos-certificates }}
       p12-password: ${{ inputs.macos-certificates-password }}
